Fix some warnings that were causing errors building with the latest Xcode
It appears the clang in the latest Xcode has better logic to detect copying caused by assigning a non reference return to a reference var.
See below the exact fixes.
Also, disabled the newly added opencl tests/build on MacOS and Windows - it was not building on MacOS, pulling linux header files.

ERROR: /Users/llitchev/local/plaidml-v1/pmlc/dialect/pxa/transforms/BUILD:23:19: C++ compilation of rule '//pmlc/dialect/pxa/transforms:transforms' failed (Exit 1)
pmlc/dialect/pxa/transforms/stencil.cc:145:22: error: loop variable 'blockArg' is always a copy because the range of type 'pmlc::dialect::pxa::BlockArgumentSet' (aka 'SmallPtrSet<mlir::BlockArgument, 8>') does not return a reference [-Werror,-Wrange-loop-analysis]
    for (const auto &blockArg : getBlockArgsAsSet()) {
                     ^
pmlc/dialect/pxa/transforms/stencil.cc:145:10: note: use non-reference type 'mlir::BlockArgument'

plaidml/op/lib/ops.cc:2908:19: error: loop variable 'dim' of type 'const plaidml::edsl::TensorDim' creates a copy from type 'const plaidml::edsl::TensorDim' [-Werror,-Wrange-loop-analysis]
  for (const auto dim : O_dims) {

ERROR: /Users/llitchev/local/plaidml-v1/pmlc/dialect/tile/BUILD:7:19: C++ compilation of rule '//pmlc/dialect/tile:tile' failed (Exit 1)
pmlc/dialect/tile/gradient.cc:87:22: error: loop variable 'operand' is always a copy because the range of type 'mlir::Operation::operand_range' (aka 'mlir::OperandRange') does not return a reference [-Werror,-Wrange-loop-analysis]
    for (const auto &operand : op->getOperands()) {
                     ^
pmlc/dialect/tile/gradient.cc:87:10: note: use non-reference type 'mlir::Value'
    for (const auto &operand : op->getOperands()) {
         ^~~~~~~~~~~~~~~~~~~~~
pmlc/dialect/tile/gradient.cc:134:22: error: loop variable 'operand' is always a copy because the range of type 'mlir::Operation::operand_range' (aka 'mlir::OperandRange') does not return a reference [-Werror,-Wrange-loop-analysis]
    for (const auto &operand : op->getOperands()) {
                     ^
pmlc/dialect/tile/gradient.cc:134:10: note: use non-reference type 'mlir::Value'
    for (const auto &operand : op->getOperands()) {
         ^~~~~~~~~~~~~~~~~~~~~
pmlc/dialect/tile/gradient.cc:216:26: error: loop variable 'dim' is always a copy because the range of type '::mlir::Operation::operand_range' (aka 'mlir::OperandRange') does not return a reference [-Werror,-Wrange-loop-analysis]
        for (const auto &dim :
                         ^
pmlc/dialect/tile/gradient.cc:216:14: note: use non-reference type 'mlir::Value'
        for (const auto &dim :
             ^~~~~~~~~~~~~~~~~
pmlc/dialect/tile/gradient.cc:239:26: error: loop variable 'dim' is always a copy because the range of type '::mlir::Operation::operand_range' (aka 'mlir::OperandRange') does not return a reference [-Werror,-Wrange-loop-analysis]
        for (const auto &dim :
                         ^
pmlc/dialect/tile/gradient.cc:239:14: note: use non-reference type 'mlir::Value'
        for (const auto &dim :
             ^~~~~~~~~~~~~~~~~
pmlc/dialect/tile/gradient.cc:307:20: error: loop variable 'dim' is always a copy because the range of type '::mlir::Operation::operand_range' (aka 'mlir::OperandRange') does not return a reference [-Werror,-Wrange-loop-analysis]
  for (const auto &dim : target_src_op.dims()) {
                   ^
pmlc/dialect/tile/gradient.cc:307:8: note: use non-reference type 'mlir::Value'
  for (const auto &dim : target_src_op.dims()) {
       ^~~~~~~~~~~~~~~~~
pmlc/dialect/tile/gradient.cc:328:20: error: loop variable 'pair' is always a copy because the range of type '::mlir::Operation::operand_range' (aka 'mlir::OperandRange') does not return a reference [-Werror,-Wrange-loop-analysis]
  for (const auto &pair : src_cons.pairs()) {
                   ^
pmlc/dialect/tile/gradient.cc:328:8: note: use non-reference type 'mlir::Value'
  for (const auto &pair : src_cons.pairs()) {
       ^~~~~~~~~~~~~~~~~~

plaidml/edsl/tests/edsl_test.cc:255:44: error: result of '2 ^ 11' is 9; did you mean '1 << 11' (2048)? [-Werror,-Wxor-used-as-pow]
  std::vector<uint64_t> C_output{1 ^ 10, 2 ^ 11, 3 ^ 12,  //
                                         ~~^~~~
                                         1 << 11